services:
  - type: web
    name: trackyard
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: TZ
        value: America/Sao_Paulo
